"""MCP Factory — Dockerfile generator for created MCP servers.

Generates a production-ready Dockerfile and .dockerignore for each
generated server, enabling one-command containerised deployment.
"""


def generate_dockerfile(name: str, language: str, template: str) -> str:
    """Return Dockerfile content for a generated MCP server.

    Args:
        name: Server name (used in labels and comments).
        language: 'typescript' or 'python'.
        template: Template name (for metadata label).

    Returns:
        Complete Dockerfile as a string.
    """
    if language == "typescript":
        return _ts_dockerfile(name, template)
    return _py_dockerfile(name, template)


def generate_dockerignore(language: str) -> str:
    """Return .dockerignore content for a generated MCP server."""
    if language == "typescript":
        return _ts_dockerignore()
    return _py_dockerignore()


# ------------------------------------------------------------------
# TypeScript
# ------------------------------------------------------------------


def _ts_dockerfile(name: str, template: str) -> str:
    return f'''# ── MCP Server: {name} ──────────────────────────────────────────
# Generated by MCP Factory
# Build:  docker build -t {name} .
# Run:    docker run -i --env-file .env {name}

# --- Build stage ---
FROM node:20-alpine AS builder
WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm ci --ignore-scripts

COPY tsconfig.json ./
COPY src/ ./src/
RUN npm run build

# --- Production stage ---
FROM node:20-alpine
WORKDIR /app

LABEL maintainer="MCP Factory"
LABEL mcpfactory.template="{template}"

COPY package.json package-lock.json* ./
RUN npm ci --omit=dev --ignore-scripts && npm cache clean --force

COPY --from=builder /app/dist ./dist

# MCP servers communicate over stdio
ENV NODE_ENV=production
ENTRYPOINT ["node", "dist/index.js"]
'''


def _py_dockerfile(name: str, template: str) -> str:
    return f'''# ── MCP Server: {name} ──────────────────────────────────────────
# Generated by MCP Factory
# Build:  docker build -t {name} .
# Run:    docker run -i --env-file .env {name}

FROM python:3.12-slim
WORKDIR /app

LABEL maintainer="MCP Factory"
LABEL mcpfactory.template="{template}"

# Install dependencies first (layer cache)
COPY pyproject.toml ./
RUN pip install --no-cache-dir . 2>/dev/null || pip install --no-cache-dir -e .

COPY . .

# MCP servers communicate over stdio
ENV PYTHONUNBUFFERED=1
ENTRYPOINT ["python", "server.py"]
'''


# ------------------------------------------------------------------
# .dockerignore
# ------------------------------------------------------------------


def _ts_dockerignore() -> str:
    return """node_modules/
dist/
.env
.git/
.gitignore
*.md
!README.md
.pytest_cache/
.vscode/
"""


def _py_dockerignore() -> str:
    return """__pycache__/
*.pyc
.env
.git/
.gitignore
*.md
!README.md
.venv/
venv/
.pytest_cache/
.vscode/
dist/
*.egg-info/
"""
